<?php

/**
 * @file
 * Contains commerce_sslcommerz.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_sslcommerz_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_sslcommerz module.
    case 'help.page.commerce_sslcommerz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SSLCommerz payment gateway for drupal8 commerce') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function commerce_sslcommerz_theme() {
  return [
    'commerce_sslcommerz' => [
      'render element' => 'children',
    ],
  ];
}
